default-catalog: local
catalog:
    local:
        uri: http://127.0.0.1:8181
        s3.endpoint: http://127.0.0.1:9000
        py-io-impl: pyiceberg.io.pyarrow.PyArrowFileIO
        s3.access-key-id: admin
        s3.secret-access-key: password
